ALTER TABLE users ADD COLUMN skills_json TEXT NOT NULL DEFAULT '[]';
ALTER TABLE users ADD COLUMN costume_flags_json TEXT NOT NULL DEFAULT '[]';
ALTER TABLE users ADD COLUMN bio TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN phone TEXT;
