import { Hono } from "hono";
import { cors } from "hono/cors";

type Env={Bindings:{DB:D1Database;ADMIN_PASSWORD?:string}};
type SessionUser={id:number|"admin";nome:string;cognome:string;username:string;role:"admin"|"user"};
const app=new Hono<Env>();const encoder=new TextEncoder();app.use("*",cors({origin:"*",allowHeaders:["Content-Type","Authorization"]}));
const DEFAULT_SKILLS=["Attore","Rievocatore","Animatore","Cavaliere","Cosplayer","Giocoliere","Public speaking","Gestione pubblico","Gestione bimbimerda"];const DEFAULT_COSTUMES=["Potter base","Medievale base","Personale 1","Personale 2"];
function bytesToHex(b:Uint8Array){return Array.from(b,x=>x.toString(16).padStart(2,"0")).join("")}function hexToBytes(h:string){const b=new Uint8Array(h.length/2);for(let i=0;i<b.length;i++)b[i]=Number.parseInt(h.slice(i*2,i*2+2),16);return b}function norm(v:string){return v.trim().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9]+/g,"").toLowerCase()}function makeUsername(n:string,c:string){return `${norm(n)}.${norm(c)}`}
async function hashPassword(p:string,saltHex?:string){const iterations=120000,salt=saltHex?hexToBytes(saltHex):crypto.getRandomValues(new Uint8Array(16)),key=await crypto.subtle.importKey("raw",encoder.encode(p),"PBKDF2",false,["deriveBits"]),bits=await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt,iterations},key,256);return `pbkdf2$${iterations}$${bytesToHex(salt)}$${bytesToHex(new Uint8Array(bits))}`}async function verifyPassword(p:string,s:string){const[a,i,sh,hh]=s.split("$");if(a!=="pbkdf2"||!i||!sh||!hh)return false;const iterations=Number(i);if(!Number.isInteger(iterations)||iterations<10000)return false;const key=await crypto.subtle.importKey("raw",encoder.encode(p),"PBKDF2",false,["deriveBits"]),bits=await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt:hexToBytes(sh),iterations},key,256),x=new Uint8Array(bits),y=hexToBytes(hh);if(x.length!==y.length)return false;let d=0;for(let j=0;j<x.length;j++)d|=x[j]^y[j];return d===0}async function hashToken(t:string){return bytesToHex(new Uint8Array(await crypto.subtle.digest("SHA-256",encoder.encode(t))))}function bearer(c:any){const v=c.req.header("Authorization");return v?.startsWith("Bearer ")?v.slice(7).trim()||null:null}
async function createSession(db:D1Database,u:SessionUser){const t=bytesToHex(crypto.getRandomValues(new Uint8Array(32))),h=await hashToken(t),e=new Date(Date.now()+604800000).toISOString();await db.prepare("INSERT INTO sessions (id,user_id,role,token_hash,expires_at) VALUES (?,?,?,?,?)").bind(crypto.randomUUID(),u.id==="admin"?null:u.id,u.role,h,e).run();return t}async function getSessionUser(db:D1Database,t:string):Promise<SessionUser|null>{const r=await db.prepare("SELECT s.role,s.user_id,s.expires_at,u.nome,u.cognome,u.username FROM sessions s LEFT JOIN users u ON u.id=s.user_id WHERE s.token_hash=?").bind(await hashToken(t)).first<any>();if(!r||new Date(r.expires_at).getTime()<=Date.now())return null;if(r.role==="admin")return{id:"admin",nome:"Admin",cognome:"",username:"admin",role:"admin"};if(r.user_id==null||!r.nome||!r.cognome||!r.username)return null;return{id:r.user_id,nome:r.nome,cognome:r.cognome,username:r.username,role:"user"}}async function requireAdmin(c:any){const t=bearer(c);if(!t)return c.json({success:false,error:"Autenticazione richiesta"},401);const u=await getSessionUser(c.env.DB,t);if(!u||u.role!=="admin")return c.json({success:false,error:"Accesso amministratore richiesto"},403);return u}
function arr(v:unknown):string[]{if(typeof v!=="string")return[];try{const x=JSON.parse(v);return Array.isArray(x)?x.filter((a):a is string=>typeof a==="string"):[]}catch{return[]}}function flags(v:unknown,allowed:string[]){return Array.isArray(v)?[...new Set(v.filter((x):x is string=>typeof x==="string"&&allowed.includes(x)))]:[]}function profile(r:any){return{id:r.id,nome:r.nome,cognome:r.cognome,username:r.username,email:r.email??null,ruolo:r.ruolo,created_at:r.created_at,phone:r.phone??null,bio:r.bio??"",skills:arr(r.skills_json),costumeFlags:arr(r.costume_flags_json)}}const SELECT="id,nome,cognome,username,email,ruolo,created_at,phone,bio,skills_json,costume_flags_json";
app.get("/api/health",c=>c.json({ok:true,service:"malastran-app-backend"}));
app.post("/api/login",async c=>{const b=await c.req.json<any>(),username=b.username?.trim().toLowerCase(),password=b.password??"";if(!username||!password)return c.json({success:false,error:"Inserisci username e password"},400);if(username==="admin"){if(!c.env.ADMIN_PASSWORD)return c.json({success:false,error:"ADMIN_PASSWORD non configurata sul backend"},500);if(password!==c.env.ADMIN_PASSWORD)return c.json({success:false,error:"Credenziali non valide"},401);const u={id:"admin",nome:"Admin",cognome:"",username:"admin",role:"admin"} as const;return c.json({success:true,token:await createSession(c.env.DB,u),user:u})}const r=await c.env.DB.prepare("SELECT id,nome,cognome,username,password_hash,ruolo FROM users WHERE lower(username)=? LIMIT 1").bind(username).first<any>();if(!r||r.ruolo!=="user"||!(await verifyPassword(password,r.password_hash)))return c.json({success:false,error:"Credenziali non valide"},401);const u={id:r.id,nome:r.nome,cognome:r.cognome,username:r.username,role:"user" as const};return c.json({success:true,token:await createSession(c.env.DB,u),user:u})});
app.get("/api/me",async c=>{const t=bearer(c);if(!t)return c.json({success:false,error:"Autenticazione richiesta"},401);const u=await getSessionUser(c.env.DB,t);if(!u)return c.json({success:false,error:"Sessione non valida o scaduta"},401);return c.json({success:true,user:u})});app.post("/api/logout",async c=>{const t=bearer(c);if(t)await c.env.DB.prepare("DELETE FROM sessions WHERE token_hash=?").bind(await hashToken(t)).run();return c.json({success:true})});
app.post("/api/admin/users",async c=>{const a=await requireAdmin(c);if(a instanceof Response)return a;const b=await c.req.json<any>(),nome=b.nome?.trim(),cognome=b.cognome?.trim(),password=b.password?.trim()||cognome||"";if(!nome||!cognome)return c.json({success:false,error:"Nome e cognome sono obbligatori"},400);if(password.length<3)return c.json({success:false,error:"La password deve contenere almeno 3 caratteri"},400);const username=makeUsername(nome,cognome);const existing=await c.env.DB.prepare("SELECT id FROM users WHERE lower(username)=? LIMIT 1").bind(username).first();if(existing)return c.json({success:false,error:`Esiste già un collaboratore con username ${username}`},409);const skills=flags(b.skills,DEFAULT_SKILLS),costumeFlags=flags(b.costumeFlags,DEFAULT_COSTUMES);const r=await c.env.DB.prepare("INSERT INTO users (nome,cognome,username,email,password_hash,ruolo,skills_json,costume_flags_json) VALUES (?,?,?,?,?,?,?,?)").bind(nome,cognome,username,b.email?.trim()||null,await hashPassword(password),"user",JSON.stringify(skills),JSON.stringify(costumeFlags)).run();return c.json({success:true,user:{id:r.meta.last_row_id,nome,cognome,username,email:b.email?.trim()||null,role:"user",skills,costumeFlags}},201)});
app.get("/api/admin/users",async c=>{const a=await requireAdmin(c);if(a instanceof Response)return a;const r=await c.env.DB.prepare(`SELECT ${SELECT} FROM users WHERE ruolo='user' ORDER BY cognome,nome`).all();return c.json({success:true,users:r.results.map(profile)})});app.get("/api/admin/users/:id",async c=>{const a=await requireAdmin(c);if(a instanceof Response)return a;const id=Number(c.req.param("id"));if(!Number.isInteger(id))return c.json({success:false,error:"ID non valido"},400);const r=await c.env.DB.prepare(`SELECT ${SELECT} FROM users WHERE id=?`).bind(id).first();if(!r)return c.json({success:false,error:"Collaboratore non trovato"},404);return c.json({success:true,user:profile(r)})});
app.get("/api/profile",async c=>{const t=bearer(c);if(!t)return c.json({success:false,error:"Autenticazione richiesta"},401);const u=await getSessionUser(c.env.DB,t);if(!u)return c.json({success:false,error:"Sessione non valida o scaduta"},401);if(u.id==="admin")return c.json({success:true,user:u});const r=await c.env.DB.prepare(`SELECT ${SELECT} FROM users WHERE id=?`).bind(u.id).first();if(!r)return c.json({success:false,error:"Profilo non trovato"},404);return c.json({success:true,user:profile(r)})});
app.patch("/api/profile",async c=>{const t=bearer(c);if(!t)return c.json({success:false,error:"Autenticazione richiesta"},401);const u=await getSessionUser(c.env.DB,t);if(!u||u.id==="admin")return c.json({success:false,error:"Profilo collaboratore non disponibile"},403);const b=await c.req.json<any>(),cur=await c.env.DB.prepare("SELECT skills_json,costume_flags_json FROM users WHERE id=?").bind(u.id).first<any>();if(!cur)return c.json({success:false,error:"Profilo non trovato"},404);const skills=b.skills===undefined?arr(cur.skills_json):flags(b.skills,DEFAULT_SKILLS),costumeFlags=b.costumeFlags===undefined?arr(cur.costume_flags_json):flags(b.costumeFlags,DEFAULT_COSTUMES);await c.env.DB.prepare("UPDATE users SET email=?,phone=?,bio=?,skills_json=?,costume_flags_json=? WHERE id=?").bind(b.email?.trim()||null,b.phone?.trim()||null,b.bio?.trim()||"",JSON.stringify(skills),JSON.stringify(costumeFlags),u.id).run();const r=await c.env.DB.prepare(`SELECT ${SELECT} FROM users WHERE id=?`).bind(u.id).first();return c.json({success:true,user:profile(r)})});
app.patch("/api/admin/users/:id/password",async c=>{const a=await requireAdmin(c);if(a instanceof Response)return a;const id=Number(c.req.param("id")),b=await c.req.json<any>(),password=b.password?.trim()??"";if(!Number.isInteger(id)||password.length<3)return c.json({success:false,error:"ID o password non validi"},400);const r=await c.env.DB.prepare("UPDATE users SET password_hash=? WHERE id=? AND ruolo='user'").bind(await hashPassword(password),id).run();if(!r.meta.changes)return c.json({success:false,error:"Collaboratore non trovato"},404);return c.json({success:true})});export default app;
